"""add facebook, linkedin

Revision ID: 5634b677d0be
Revises: 45e78065277c
Create Date: 2023-04-05 00:16:13.512779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5634b677d0be'
down_revision = '45e78065277c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
