"""add posts table

Revision ID: 58467bf6c9a4
Revises: a4124b97a504
Create Date: 2023-04-04 18:39:16.129256

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '58467bf6c9a4'
down_revision = 'a4124b97a504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='fk_posts_author_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
