"""move lastseen to profile

Revision ID: a4124b97a504
Revises: 101f7547c548
Create Date: 2023-04-04 03:16:36.873817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4124b97a504'
down_revision = '101f7547c548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
