"""empty message

Revision ID: dba416118885
Revises: 5634b677d0be
Create Date: 2023-04-05 11:02:20.997126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba416118885'
down_revision = '5634b677d0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dislikes_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_dislikes_post_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_dislikes_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_dislikes_post_id', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_likes_post_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_likes_post_id', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_likes_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_post_id', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_likes_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dislikes_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_dislikes_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_dislikes_post_id', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_dislikes_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
