"""cascade delete

Revision ID: f401d768f8f2
Revises: 58467bf6c9a4
Create Date: 2023-04-04 23:36:52.969565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f401d768f8f2'
down_revision = '58467bf6c9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_author_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_author_id', 'user', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_profiles_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_profiles_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_author_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_author_id', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###
