"""add profiles table

Revision ID: f69f65fe4dd8
Revises: 1ab21381840f
Create Date: 2023-04-02 17:04:42.792312

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f69f65fe4dd8'
down_revision = '1ab21381840f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('bio', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_profiles_user_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
